### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by DkmS1953** [karlkoorna/shozom#1]
Собрал программу в VS 2022, запустил и получил сообщение о наличии трояна (критический уровень).
I built the program in VS 2022, launched it and received a message about the presence of a Trojan (critical level).

![image](https://user-images.githubusercontent.com/25905429/135529694-40c0f31f-d605-468f-938a-a62853a402a4.png)

Сама программа работает как должно быть.
The program itself works as it should.

**Comment by karlkoorna** [comment]
False positive, could be because of the interaction with audio devices.

In general, false positives are quite common when building unknown programs like this from source,
as the source code is available in full I do not consider this a must-fix issue.

Hope you enjoy the program ❤️

**Comment by DkmS1953** [comment]
I did the same with another similar [program](https://github.com/AlekseyMartynov/shazam-for-real) there are no adventures with "Trojans" there.
There is a slightly different set of NuGet pluggable packages.
Maybe this is the case?

**Comment by karlkoorna** [comment]
Fair point, could also be because of the .tmp images for the toast being written to the temp folder.

On my system Windows Defender says it scanned it and that nothing was detected.
Running the executable through virustotal.com has only 1 detection for 66 checkers.
